### ISSUE TITLE
Remove of STS break our usage of the plugin

### ISSUE THREAD

**Issue by marcelobartsch** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#79] opened 2021-02-11 13:54 UTC
with #43 , it break the plugin for us, we where using it without issues referencing ARNs in our pipelines (luckily we have it only in one so far), we revert to 0.5.2 to have that functionality back.

any chance you can re-introduce it ?

**Comment by chriskilding** [comment] 2021-02-11 15:11
Hi Marcelo, I took the feature out because I couldn't reliably reproduce the cases where it broke for me. As a result I was concerned that it could be breaking for other users too.

I do want Jenkins to better support multi-account/environment/cloud setups, so I intend to bring the feature back in future - with one or two changes to make it safer.

The solution I am thinking about is to introduce a new concept - namespaces - into the credentials API plugin, which would allow credentials from multiple cloud accounts (or any similar kind of source) to coexist safely within Jenkins, even when they have the same names.

A `credentials` binding in your Jenkinsfile would look like this:

```groovy
pipeline {
    agent any
    stages {
        stage('Deploy to staging') {
            environment {
                API_KEY = credentials('api-key', namespace: '1111111111')
            }
            steps {
                sh 'curl -X POST -u "foo:$API_KEY" https://example.com'
            }
        }
        stage('Deploy to production') {
            environment {
                API_KEY = credentials('api-key', namespace: '2222222222')
            }
            steps {
                sh 'curl -X POST -u "foo:$API_KEY" https://example.com'
            }
        }
    }
}
```

A `withCredentials` binding would look like this:

```groovy
node {
    withCredentials(bindings: [string(credentialsId: 'api-key', variable: 'API_KEY', namespace: '1111111111')]) {
        echo 'Hello world'
    }
}
```

Meanwhile credentials in the default namespace would continue to be accessed as they are today, with no namespace argument. My initial idea is that credentials from providers that don't support the `namespace` argument (i.e. any currently existing provider) are deemed to be in the default namespace. And it's up to the provider to decide how to implement the `namespace` argument.

I've been wanting to push this idea forward for a little while, but it was missing one thing - a user who needs the feature, who can help guide the development of it and drive it forward. You and your team would fit the bill perfectly :)

If you're interested in helping, I'll raise the idea on the mailing list and loop you in?

**Comment by marcelobartsch** [comment] 2021-02-11 18:36
Where do I sign for this!! 
I have seen , for example the ParameterStore plugin use another approach, where you can pass the credentials on the pipeline to define which credentials to use, allowing , for example multiple AWS STS Roles, I know is not the same way you are planning, but can also provide some level of 'separation' or 'namespacing' on the credentials allowing multiple roles/accounts to be used on the pipelines, and delegating the separation of credentials to other plugins instead of creating a new one? BUT i'm may misunderstand the namespace idea in jenkins as I'm not a developer and more a user-level admin in jenkins.

https://plugins.jenkins.io/aws-parameter-store/

**Comment by chriskilding** [comment] 2021-02-12 11:43
I've posted to the jenkinsci-dev mailing list to start a discussion about this. You can view it in browser at https://groups.google.com/g/jenkinsci-dev/c/rmhp4sQrK0I. Alternatively you can subscribe to the mailing list here: https://www.jenkins.io/mailing-lists/

**Comment by chriskilding** [comment] 2021-02-23 17:33
Just to let you know that this is one of the discussion topics at the Jenkins Contributor Summit online, in sessions between now and Thursday.

**Comment by chriskilding** [comment] 2022-05-24 09:52
@marcelobartsch If you're still watching this issue - it's now possible in plugin v1.1.0 to specify a custom IAM role in the Secrets Manager client configuration. This should let the plugin access secrets in a *different* account to the one Jenkins is running in (though not *multiple* accounts). Give it a go and let me know if it works for you.

**Comment by chriskilding** [comment] 2022-07-22 16:25
Closing because `sts:assumeRole` support was added back to the plugin

**Closed by chriskilding** 2022-07-22 16:25 UTC
