### ISSUE TITLE
Make this plugin configurable at folder level, not just centrally

### ISSUE THREAD

**Issue by edwardprzeniczny** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#261] opened 2023-01-25 10:34 UTC
### What feature do you want to see added?

This plugin is only configurable at system config. In an environment where is the segregation, the ability to configure at a folder level so teams can configure the role used to lookup credentials, the filters etc and then storing the credentials within that folder would solve many issues. The vault plugin has the ability to configure (although its not storing) at folder level.

**Comment by chriskilding** [comment] 2023-01-25 18:19
Hi Edward,

Could you give me some more information about your usage scenario? You mentioned that you have a segregated configuration; does this mean you that have one Jenkins to orchestrate multiple environments (e.g. staging, production), or perhaps one multi-tenant Jenkins shared by many teams?

**Comment by edwardprzeniczny** [comment] 2023-01-26 11:32
@chriskilding Hi

So I guess segregation can be viewed in multiple ways.

In our setup, we manage the infrastructure. Development teams have a folder on 1 or many instances which is "protected" with RBAC. Since teams will have their own credentials for accessing varying services, we dont want to store credentials globally to prevent accidental use and naming collisions. Also the teams have their own AWS accounts where they can store their credentials and create the relevant IAM roles for our instances to have trusted access.

Being able to set a role at a folder level means that teams can lookup and populate their folder credentials using the role and  filters - they can then segregate in sub folders if there is any requirement - without requiring to reach out to central managment team (apart from initial setup). There will less requirement to pass credentials around or create convoluted processes.

Centrally provisioned credentials can then still be set globally and controlled by us

I hope this makes it clearer

**Comment by chriskilding** [comment] 2023-01-30 11:18
You mentioned that "development teams have a folder on 1 or many instances". This needs a bit of clarification.

If (many) development teams are using 1 instance, that's what I would call 'multi-tenant Jenkins'.

However if they are on many instances, that could mean that this is not in fact a multi-tenant setup, and teams are assigned their own Jenkins servers (though they may not have full management responsibility for the server themselves).

Could you clarify which of these scenarios is the one that your company uses?

**Comment by edwardprzeniczny** [comment] 2023-01-30 12:40
The default configuration is to assume multi-tenancy

**Comment by chriskilding** [comment] 2023-01-31 11:48
I've tried adapting Vault's folder configuration class into this plugin just to see if that would work. However when I launched it, the configuration item doesn't appear in folder configuration.

I thought I'd check the Vault plugin to see if there were any issues along these lines, and indeed I then saw a couple of issues reported from people who couldn't get folder-level configuration to work. Interestingly the FolderVaultConfiguration class is not actually referenced anywhere in the Vault plugin code, except by unit tests. Unless the class is loaded indirectly (e.g. a reflection-based `AbstractFolderProperty<AbstractFolder<?>>` loader), this might explain it.

If you are using the Vault plugin, have you been able to make folder-level configuration work? If so could you upload a screenshot?

**Comment by chriskilding** [comment] 2023-02-17 12:04
An update: development of this feature is now proceeding in an extension plugin, https://github.com/chriskilding/aws-secrets-manager-credentials-provider-folders-plugin/

The idea is this will behave very similarly to the main plugin (supports all the same credential types, and configuration properties), with 2 differences:

- The plugin is configured at the folder level (on the Cloudbees Folder object's properties), not the global level
- Credentials from the extension plugin are scoped to the folder-level (i.e. only visible in the relevant folder and its subfolders)

In future, you'll be able to use this plugin and the extension plugin in 3 different ways:

- **Together:** This means you'll get both global credentials from this plugin, and folder-scoped credentials from the extension
- **Just global credentials:** Use just this plugin like you do today, and you'll only get global-scoped credentials
- **Just folder-scoped credentials:** Use only the extension plugin (which will be decoupled from this plugin in the future), and you will only get folder-scoped credentials

I'm looking for initial feedback on a super early stage version of it, so if you (or anyone watching this issue) would like to alpha test it and provide feedback, please head over to https://github.com/chriskilding/aws-secrets-manager-credentials-provider-folders-plugin/pull/1 and indicate your interest :)

**Comment by chriskilding** [comment] 2023-02-17 12:06
This issue is now effectively a duplicate of #161 , so I'll close this one and loop you all into the other issue.

**Closed by chriskilding** 2023-02-17 12:06 UTC
Labels: enhancement
