### ISSUE TITLE
Icons don't display for "SSH User Private Key" & "Certificate" credentials types

### ISSUE THREAD

**Issue by exoaturner** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#246] opened 2022-10-17 08:48 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.361.2.1
OS: Linux - 5.4.209-116.367.amzn2.x86_64
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-cloudformation:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-codebuild:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ec2:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-ecr:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ecs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-elasticbeanstalk:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-iam:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-logs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-minimal:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-sns:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-sqs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ssm:1.12.246-349.v96b_b_f7eb_a_c3c
aws-secrets-manager-credentials-provider:1.2.0
blueocean-commons:1.25.8
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.0-1
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.5
cloudbees-administrative-monitors:1.0.5
cloudbees-analytics:1.42
cloudbees-assurance:2.276.0.23
cloudbees-blueocean-default-theme:0.8
cloudbees-folder:6.758.vfd75d09eea_a_1
cloudbees-folders-plus:3.29
cloudbees-github-reporting:1.31
cloudbees-groovy-view:1.14
cloudbees-jenkins-advisor:3.3.3
cloudbees-jsync-archiver:5.25
cloudbees-license:9.68
cloudbees-monitoring:2.15
cloudbees-nodes-plus:1.24
cloudbees-platform-common:1.18
cloudbees-platform-data:1.29
cloudbees-plugin-usage:2.17
cloudbees-ssh-slaves:2.19
cloudbees-support:3.30
cloudbees-template:4.58
cloudbees-uc-data-api:4.50
cloudbees-unified-ui:1.22
cloudbees-view-creation-filter:1.9
cloudbees-workflow-template:3.18
cloudbees-workflow-ui:2.8
command-launcher:84.v4a_97f2027398
credentials:1143.vb_e8b_b_ceee347
credentials-binding:523.vd859a_4b_122e6
display-url-api:2.3.6
durable-task:500.v8927d9fd99d8
echarts-api:5.3.3-1
email-ext:2.91
font-awesome-api:6.1.2-1
git:4.11.5
git-client:3.11.2
github:1.35.0
github-api:1.303-400.v35c2d8258028
github-branch-source:1695.v88de84e9f6b_9
gradle:1.39.4
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
infradna-backup:3.38.56
instance-identity:116.vf8f487400980
jackson2-api:2.13.3-285.vc03c0256d517
jakarta-activation-api:2.0.1-1
jakarta-mail-api:2.0.1-1
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jaxb:2.3.6-1
jdk-tool:55.v1b_32b_6ca_f9ca
jjwt-api:0.11.5-77.v646c772fddb_0
jquery3-api:3.6.0-4
jsch:0.1.55.61.va_e9ee26616e7
junit:1119.1121.vc43d0fc45561
kube-agent-management:1.1.56
kubernetes:3697.v771155683e38
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
ldap:2.12
mailer:438.v02c7f0a_12fa_4
mapdb-api:1.0.9-28.vf251ce40855d
matrix-project:785.v06b_7f47b_c631
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.9.1-44.v476733c11f82
mina-sshd-api-core:2.9.1-44.v476733c11f82
mina-sshd-api-scp:2.9.1-44.v476733c11f82
mina-sshd-api-sftp:2.9.1-44.v476733c11f82
momentjs:1.1.1
nectar-license:8.41
nectar-rbac:5.76
node-iterator-api:49.v58a_8b_35f8363
oauth-credentials:0.5
okhttp-api:4.9.3-108.v0feda04578cf
operations-center-agent:2.361.0.1
operations-center-client:2.361.0.1
operations-center-cloud:2.361.0.2
operations-center-context:2.361.0.2
pipeline-build-step:2.18
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:612.v84da_9c54906d
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2114.v2654ca_721309
pipeline-model-definition:2.2114.v2654ca_721309
pipeline-model-extensions:2.2114.v2654ca_721309
pipeline-rest-api:2.24
pipeline-stage-step:296.v5f6908f017a_5
pipeline-stage-tags-metadata:2.2114.v2654ca_721309
pipeline-stage-view:2.24
plain-credentials:139.ved2b_9cf7587b
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.6-1
scm-api:621.vda_a_b_055e58f7
script-security:1175.v4b_d517d6db_f0
snakeyaml-api:1.31-84.ve43da_fb_49d0b
ssh-credentials:305.v8f4381501156
sshd:3.249.v2dc2ea_416e33
structs:324.va_f5d6774f3a_d
support-core:1206.v14049fa_b_d860
token-macro:308.v4f2b_ed62b_b_16
trilead-api:2.72.v2a_3236754f73
unique-id:2.2.1
user-activity-monitoring:1.8
variant:59.vf075fe829ccb
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1192.v2d0deb_19d212
workflow-basic-steps:994.vd57e3ca_46d24
workflow-cps:2759.v87459c4eea_ca_
workflow-cps-checkpoint:2.13
workflow-durable-task-step:1199.v02b_9244f8064
workflow-job:1232.v5a_4c994312f1
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:838.va_3a_087b_4055b
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller is running in a container on k8s, the host is Amazon Linux.

### Reproduction steps

Create secrets for the plugin with the below types in AWS:

 - SSH User Private Key
- Certificate

View secrets in Credentials menu inside of the controller.

### Expected Results

All icons are displayed for all credentials types.

### Actual Results

Icons for the below secret types are not displayed.

 - SSH User Private Key
- Certificate

### Anything else?

Technically we are not running plain Jenkins, our Jenkins controller was setup using CloudBees CI operations center.

This was also tested when these secret types are created locally in Jenkins controller and the icons display correctly, which suggests an issue with the plugin and not Jenkins.

Image of the problem:

![Issue](https://i.imgur.com/baqke7g.png)

Image of the differences in HTML (IMG vs SVN):

![Issue html](https://i.imgur.com/bGp9uXE.png)

**Comment by chriskilding** [comment] 2022-10-31 18:13
I believe this was caused by the credentials API plugin moving to a new icon for these credential types. The new icons have different names to the old icons. Because the AWS provider credentials still use the old icon names, they're now out of sync with the credentials API plugin - that's why you don't see the correct icon for them (or you see a broken icon.

The changes I've seen are:

- SSH key: `icon-fingerprint` -> `symbol-fingerprint`
- Certificate: `icon-credentials-certificate` -> `icon-application-certificate`

In #216 I updated the icon used for the SSH key. Your bug report shows that other credential types may also have new icons. Could you let me know the new icon name for the Certificate type (and maybe the other main credential types) that you see in your Web inspector console? That way I can include these fixes in the PR as well.

**Comment by exoaturner** [comment] 2022-11-01 08:22
Thanks @chriskilding 

I went through each of the secrets your plugin supports. I hope the below is useful:

string (Kind: secret text) -> `symbol-key`

![string](https://i.imgur.com/E7fjEh4.png)

usernamePassword (Kind: Username with password) -> `symbol-id-card`

![usernamePassword ](https://i.imgur.com/F79KqIS.png)

sshUserPrivateKey (Kind: SSH Username with private key) -> `symbol-fingerprint`

![sshUserPrivateKey ](https://i.imgur.com/bDu8fKX.png)

certificate (Kind: certificate) -> `icon-application-certificate`

![certificate](https://i.imgur.com/42YwAyK.png)

file (Kind: Secret file) -> `symbol-key`

![file](https://i.imgur.com/0n1TChn.png)

Kind regards,
Aaron

**Comment by chriskilding** [comment] 2022-11-01 12:49
Thanks :)

The AWS implementations of the String and File credentials don't override getIconClassName(). This means they inherit the credentials API plugin's default icon name. That stays current with whatever the default credentials provider does, so essentially it's always correct.

The only credential types that need updating in code are the ones that do override getIconClassName. That obviously includes SSH Key and Certificate. It also includes Username and Password. I'll get those done in #216.

For the Certificate type, it looks like there is a further change coming down the pipe; the new name is `icon-application-certificate`, however if you look in Jenkins core, you see they've changed this *again* to `symbol-ribbon`. This change has not yet propagated to the Credentials API plugin but it will do eventually. This means we're looking at another breaking icon change down the line.

**Closed** 2022-11-02 22:05 UTC
Labels: bug

**Comment by chriskilding** [comment] 2022-11-04 15:05
Hi, version 1.198.v839f082578db is now released which contains fixes for the icons as they stand today.

If you could install that and confirm whether it fixes the issues you saw, that would be great.

Btw the new minimum supported Jenkins version of the plugin is 2.346.3
